k9s:
  ui:
    skin: catppuccin-latte
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  shellPod:
    image: killerAdmin
    namespace: default
    tty: true
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 1000
    buffer: 5000
    sinceSeconds: 300
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-mcritchlow
  disablePodCounting: false
